---
# Source: argo-cd/templates/repo-server/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-cd-repo-server
  namespace: "argo-cd"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-3.3.4
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
