---
# Source: argo-cd/templates/application-controller/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cd-app-controller
  namespace: "argo-cd"
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-3.3.4
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cd-app-controller
subjects:
  - kind: ServiceAccount
    name: argo-cd-argocd-app-controller
    namespace: argo-cd
