name: Go

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pkg/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...


  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: "--out-${NO_FUTURE}format colored-line-number"
          version: v1.46.0
          # only-new-issues: true
          skip-cache: true
          skip-build-cache: true
