name: Update Sealed Secrets manifests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/secrets/**'

jobs:
  update-ss-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup git-crypt
        run: sudo apt-get install -y git-crypt

      - name: Setup kubeseal
        run: |
          brew install yq
          latest_version_name="$(curl -sH "Accept: application/vnd.github.v3+json" https://api.github.com/repos/bitnami-labs/sealed-secrets/releases | jq -r "map(select(.prerelease == false)) | .[0].name")"
          latest_version="${latest_version_name#"sealed-secrets-v"
          curl -sL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${latest_version}/kubeseal-${latest_version}-linux-amd64.tar.gz" | tar -xz kubeseal
          mv kubeseal /usr/local/bin/kubeseal
          chmod +x /usr/local/bin/kubeseal

      - name: Unlock secrets
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      # ... THIS BLOCK ASSUMES USING GKE
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Get staging cluster credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: staging-cluster # TO BE UPDATED
          location: us-central1 # TO BE UPDATED
      # END OF BLOCK

      - name: Update staging Sealed Secrets manifests
        run: ./scripts/create-ss-manifests.sh --target staging --service-info ./infrastructure/build/services.json
        shell: bash

      # ... THIS BLOCK ASSUMES USING GKE
      - name: Get staging cluster credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: production-cluster # TO BE UPDATED
          location: us-central1 # TO BE UPDATED
      # END OF BLOCK

      - name: Update production Sealed Secrets manifests
        run: ./scripts/create-ss-manifests.sh --target production --service-info ./infrastructure/build/services.json
        shell: bash

      - name: Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: 'infrastructure/kubernetes'
          message: 'fix: update Sealed Secrets manifests'
